CREATE DATABASE CLIENTEAPIREST;

USE CLIENTEAPIREST;
CREATE TABLE clientes(
id INT PRIMARY KEY AUTO_INCREMENT,
dni VARCHAR(11) NOT NULL,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
fecha_nacimiento DATE
);
