USE PROYECTO_FINAL;
CREATE TABLE CLIENTES(
DNI INT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50),
);

USE PROYECTO_FINAL;
CREATE TABLE PRODUCTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NEMO_PRODUCTO VARCHAR(10) NOT NULL UNIQUE,
DESCRIPCION_PRODUCTO VARCHAR(30),
PRECIO INT NOT NULL
);

USE PROYECTO_FINAL;
CREATE TABLE VENTAS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUCTO INT NOT NULL,
CANTIDAD_PRODUCTO INT NOT NULL,
ID_CLIENTE INT,
TOTAL_VENTA INT NOT NULL,
FECHA_VENTA DATE NOT NULL,
CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY(PRODUCTOS) REFERENCES PRODUCTOS(ID),
CONSTRAINT FK_ID_CLIENTE FOREIGN KEY(CLIENTES) REFERENCES CLIENTES(DNI)
);

USE PROYECTO_FINAL;
CREATE TABLE STOCK(
ID_PRODUCTO INT PRIMARY KEY,
STOCK INT,
CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY(PRODUCTOS) REFERENCES PRODUCTOS(ID)
);